version: '3'
services:

  configurator:
    container_name: senzing-configurator
    environment:
#     See https://github.com/Senzing/configurator#configuration
      SENZING_ENGINE_CONFIGURATION_JSON: >-
        {
          "PIPELINE": {
            "CONFIGPATH": "/etc/opt/senzing",
            "LICENSESTRINGBASE64": "${SENZING_LICENSE_BASE64_ENCODED}",
            "RESOURCEPATH": "/opt/senzing/g2/resources",
            "SUPPORTPATH": "/opt/senzing/data"
          },
          "SQL": {
            "BACKEND": "SQL",
            "CONNECTION": "${SENZING_SQL_CONNECTION:-postgresql://postgres:postgres@senzing-postgres:5432:G2/"
          }
        }
    image: senzing/configurator:${SENZING_DOCKER_IMAGE_VERSION_CONFIGURATOR:-latest}
    networks:
      - senzing
    ports:
      - 8253:8253
    read_only: true
    restart: always

networks:
  senzing:
    external: true
    name: ${SENZING_DOCKER_NETWORK:-senzing-network}
